PROMSIED_DOWN= # YOUR PROMISED DOWN SPEED
PROMSIED_UP= # YOUR PROMISED UP SPEED
CHROME_DRIVER_PATH= # YOUR CHROME DRIVER PATH
TWITTER_EMAIL= # YOUR TWITTER EMAIL ID
TWITTER_PASSWROD= # YOUR TWITTER PASSWORD
SPEED_TEST="https://www.speedtest.net/"
TWITTER_URL="https://twitter.com/"