SHEETY_AUTH= # YOUR SHEETY AUTH KEY
KIWI_API_KEY=# YOUR TEQUILA API KEY
MY_NUMBER = # YOUR PERSONAL NUMBER
TWILIO_NUMBER =# YOUR TWILIO PHONE NUMBER
account_sid = # YOUR TWILIO ACCOUNT SID
auth_token = # YOUR TWILIO AUTH TOKEN